---
title: "Predicting Income with Social Data"


# load packages and data
library(ggplot2)
library(dplyr)
library(modelr)
psid <- read.csv("psid_2017.csv")

# view data structure
str(psid)

# plot age
age_dist <- psid %>%
  ggplot(aes(age)) +
  geom_bar()

age_dist

# filter to reasonable age group
psid_clean <- psid %>% 
  filter(!(age < 18 | age > 75))


# plot flitered age
age_dist <- psid_clean %>%
  ggplot(aes(age)) +
  geom_bar()
age_dist

# plot education
educ_dist <- psid_clean %>%
  ggplot(aes( education_years, education_years)) +
  geom_boxplot()
 
# view plot
educ_dist

# filter to reasonable education levels
psid_clean <- psid_clean %>% 
  filter(education_years > 5, education_years < 25)

# plot income
income <- psid_clean %>%
  ggplot(aes( labor_income , labor_income )) +
geom_boxplot() 

income

# view income summary statistics
summary(psid_clean$labor_income)

# plot mean income by age
mean_income_by_age <- psid_clean%>%
  group_by(age) %>%
  summarise(mean_income = mean(labor_income)) %>%
  ggplot(aes(age, mean_income)) +
  geom_point() 
 
# view plot
mean_income_by_age


# subset data points into train and test sets
set.seed(123)
sample <- sample(c(TRUE, FALSE), nrow(psid_clean), replace = T, prob = c(0.6,0.4))

# define train and test

train <- psid_clean[sample, ]
test <- psid_clean[!sample, ]

# build model
model <- lm(labor_income ~ education_years , data = train)


# plot against LOESS model
plot <- ggplot(train, aes(education_years, labor_income)) +
  geom_point() + 
  geom_smooth(method = "lm") + 
  geom_smooth(se = FALSE, color = "red")
 
# view plot
plot 


# compute r-squared
r_sq <- summary(model)$r.squared * 100

# uncomment to write out r-squared interpretation
sprintf("Based on a simple linear regression model, we have determined that %s percent of the variation in respondent income can be predicted by a respondent's education level.", r_sq)

# build second model
model_2 <- lm(labor_income ~ education_years + age + gender , data = train)
r_sq_2 <- summary(model_2)$r.squared * 100

# uncomment to write out r-squared interpretation
sprintf("Based on a simple linear regression model, we have determined that %s percent of the variation in respondent income can be predicted by a respondent's education level, age and gender.", r_sq_2)

# plot predictions versus observed
plot <- test %>% 
  add_predictions(model_2) %>%
  ggplot(aes(age, labor_income)) +
  geom_point() +
  geom_line(aes(y = pred), color = "blue") 
 
# view plot 
plot

# write out model results
summary(model_2)

# extract education coefficent
education_coefficent <- model_2$coefficients[2] 

# uncomment to write out coefficent interpretation
sprintf("Based on a multiple linear regression model of education, age, and gender, for every additional year of formal education, the average American resident's income increases by $%s.", education_coefficent)
```